
name: 'Terraform Deployment to azure sandbox'

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch: 

defaults:
  run:
    shell: bash

env:
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
  STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
  ROOT_PATH: "../terraform"
  STAGE_NAME: development

###

jobs:

  terraform_validate:
    name: 'Terraform Validate'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    
      - name: Terraform Init
        run: terraform init 
          -backend-config="storage_account_name=${{env.STORAGE_ACCOUNT}}" 
          -backend-config="container_name=${{env.CONTAINER_NAME}}" 
          -backend-config="resource_group_name=${{env.RESOURCE_GROUP}}"
          -backend-config="key=terraform.tfstate"
        working-directory: "./terraform"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: "./terraform"

  terraform_plan:
    name: 'Terraform Plan'
    needs: [terraform_validate]
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init 
          -backend-config="storage_account_name=${{env.STORAGE_ACCOUNT}}" 
          -backend-config="container_name=${{env.CONTAINER_NAME}}" 
          -backend-config="resource_group_name=${{env.RESOURCE_GROUP}}"
          -backend-config="key=terraform.tfstate"
        working-directory: ${{env.ROOT_PATH}}

      - name: Terraform Plan
        run: terraform plan -lock=false
        working-directory: ${{env.ROOT_PATH}}
        

  terraform_apply:
    name: 'Terraform Apply'
    needs: [terraform_plan]
    runs-on: ubuntu-latest
    environment: development

    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init 
          -backend-config="storage_account_name=${{env.STORAGE_ACCOUNT}}" 
          -backend-config="container_name=${{env.CONTAINER_NAME}}" 
          -backend-config="resource_group_name=${{env.RESOURCE_GROUP}}"
          -backend-config="key=terraform.tfstate"
      
      - name: Terraform Apply
        # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -lock=false
        working-directory: ${{env.ROOT_PATH}}
